JARO_WEIGHT_STRING_A = 1.0 / 3.0
JARO_WEIGHT_STRING_B = 1.0 / 3.0
JARO_WEIGHT_TRANSPOSITIONS = 1.0 / 3.0 

JARO_WINKLER_PREFIX_SIZE = 40
JARO_WINKLER_SCALING_FACTOR = 0.01
JARO_WINKLER_BOOST_THRESHOLD = 0.7

